/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module map_3 (
    input clk,
    input rst,
    input next,
    input [2:0] level,
    output reg [399:0] out
  );
  
  
  
  reg [399:0] def;
  
  reg [0:0] M_start_d, M_start_q = 1'h0;
  reg [399:0] M_map_d, M_map_q = 1'h0;
  reg [255:0] M_startPos_d, M_startPos_q = 1'h0;
  
  always @* begin
    M_start_d = M_start_q;
    M_map_d = M_map_q;
    
    
    case (level)
      1'h1: begin
        def = 400'h00000000000a0a000808040401edec0303014544000001f5f40a0a000808040401edec030301454400000145440000000000;
      end
      2'h2: begin
        def = 400'h00000000000a1a000808040442121003030144440008020a080a0802080804740212103b0302c544204003f6080000000000;
      end
      default: begin
        def = 400'h00000000000a00000000000001e0ec0303014544000001f5f40a0a000808040401edec030301454400000145440000000000;
      end
    endcase
    if (~M_start_q) begin
      M_map_d = def;
      M_start_d = 1'h1;
    end
    out = M_map_q;
    if (next) begin
      M_start_d = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_start_q <= 1'h0;
      M_map_q <= 1'h0;
      M_startPos_q <= 1'h0;
    end else begin
      M_start_q <= M_start_d;
      M_map_q <= M_map_d;
      M_startPos_q <= M_startPos_d;
    end
  end
  
endmodule
