/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module checkLeftRight_16 (
    input [399:0] map,
    input [399:0] position,
    input [0:0] leftRight,
    output reg [0:0] out,
    output reg [0:0] outerWall
  );
  
  
  
  integer loop;
  
  reg [7:0] a;
  
  reg [7:0] b;
  
  reg [7:0] c;
  
  reg [7:0] result1;
  
  reg [7:0] result2;
  
  reg [7:0] result3;
  
  localparam OUTERWALL = 400'hffffffffffc0003c0003c0003c0003c0003c0003c0003c0003c0003c0003c0003c0003c0003c0003c0003c0003ffffffffff;
  
  always @* begin
    out = 1'h1;
    outerWall = 1'h0;
    for (loop = 2'h2; loop < 5'h12; loop = loop + 1'h1) begin
      if ((|position[(loop)*20+19-:20])) begin
        if (leftRight) begin
          if ((~|((position[(loop)*20+19-:20] >> 1'h1) & map[(loop)*20+19-:20]))) begin
            if ((~|((position[(loop)*20+19-:20] >> 1'h1) & OUTERWALL[(loop)*20+19-:20]))) begin
              out = 1'h0;
            end else begin
              outerWall = 1'h1;
            end
          end
        end else begin
          if ((~|((position[(loop)*20+19-:20] << 1'h1) & map[(loop)*20+19-:20]))) begin
            if ((~|((position[(loop)*20+19-:20] << 1'h1) & OUTERWALL[(loop)*20+19-:20]))) begin
              out = 1'h0;
            end else begin
              outerWall = 1'h1;
            end
          end
        end
      end
    end
  end
endmodule
