/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module checkWin_11 (
    input [399:0] position,
    input [399:0] winPos,
    output reg out
  );
  
  
  
  integer loop;
  
  always @* begin
    out = 1'h0;
    for (loop = 2'h2; loop < 5'h12; loop = loop + 1'h1) begin
      if ((|position[(loop)*20+19-:20])) begin
        if ((|(position[(loop)*20+19-:20] & winPos[(loop)*20+19-:20]))) begin
          out = 1'h1;
        end
      end
    end
  end
endmodule
