/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module checkUpDown_9 (
    input [0:0] upDown,
    input [399:0] map,
    input [399:0] position,
    output reg out
  );
  
  
  
  integer loop;
  
  reg [7:0] a;
  
  reg [7:0] b;
  
  reg [7:0] c;
  
  reg [7:0] result1;
  
  reg [7:0] result2;
  
  reg [7:0] result3;
  
  localparam OUTERWALL = 400'hffffffffffc0003c0003c0003c0003c0003c0003c0003c0003c0003c0003c0003c0003c0003c0003c0003c0003ffffffffff;
  
  always @* begin
    out = 1'h1;
    for (loop = 2'h2; loop < 5'h12; loop = loop + 1'h1) begin
      if ((|position[(loop)*20+19-:20])) begin
        if (upDown) begin
          a = position[(loop)*20+10+7-:8];
          b = map[(loop + 1'h1)*20+10+7-:8];
          c = OUTERWALL[(loop + 1'h1)*20+10+7-:8];
          if ((~|(position[(loop)*20+19-:20] & map[(loop + 1'h1)*20+19-:20]))) begin
            if ((~|(position[(loop)*20+19-:20] & OUTERWALL[(loop + 1'h1)*20+19-:20]))) begin
              out = 1'h0;
            end
          end
        end else begin
          a = position[(loop)*20+12+5-:6];
          b = map[(loop - 1'h1)*20+12+5-:6];
          c = OUTERWALL[(loop - 1'h1)*20+12+5-:6];
          if ((~|(position[(loop)*20+19-:20] & map[(loop - 1'h1)*20+19-:20]))) begin
            if ((~|(position[(loop)*20+19-:20] & OUTERWALL[(loop - 1'h1)*20+19-:20]))) begin
              out = 1'h0;
            end
          end
        end
      end
    end
  end
endmodule
