/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module dffTester_2 (
    input clk,
    input rst,
    output reg blink,
    input rar
  );
  
  
  
  
  localparam OFF_counter = 1'd0;
  localparam ON_counter = 1'd1;
  
  reg M_counter_d, M_counter_q = OFF_counter;
  
  reg [0:0] on;
  
  always @* begin
    M_counter_d = M_counter_q;
    
    blink = 1'h0;
    
    case (M_counter_q)
      OFF_counter: begin
        blink = 1'h0;
        if (rar) begin
          M_counter_d = ON_counter;
        end
      end
      ON_counter: begin
        blink = 1'h1;
        if (rar) begin
          M_counter_d = OFF_counter;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
endmodule
