/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  reg [7:0] a;
  
  reg [7:0] b;
  
  reg [5:0] aLUFN;
  
  wire [8-1:0] M_alufn_out;
  wire [3-1:0] M_alufn_zvn;
  reg [8-1:0] M_alufn_a;
  reg [8-1:0] M_alufn_b;
  reg [6-1:0] M_alufn_aLUFN;
  alufn_1 alufn (
    .a(M_alufn_a),
    .b(M_alufn_b),
    .aLUFN(M_alufn_aLUFN),
    .out(M_alufn_out),
    .zvn(M_alufn_zvn)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    a = io_dip[0+7-:8];
    b = io_dip[8+7-:8];
    aLUFN = io_dip[16+0+5-:6];
    M_alufn_a = a;
    M_alufn_b = b;
    M_alufn_aLUFN = aLUFN;
    io_led[0+7-:8] = M_alufn_out;
    io_led[16+0+2-:3] = M_alufn_zvn;
  end
endmodule
